check:
  global:
    statements: 50
    lines: 30
    branches: 25
    functions: 40
    excludes: []
    each:
      statements: 0
      lines: 0
      branches: 0
      functions: 0
      excludes: []
